POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "abc",
    "number": "123456789"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "null",
    "number": "0"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Arto Hellas",
    "number": "01234"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Delete me",
    "number": "123"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "me",
    "number": "123"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "you",
    "number": "123-4567"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "she",
    "number": "12-345678"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "we",
    "number": "12-0"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "him",
    "number": "1-4567"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "they",
    "number": "1456789"
}