POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "abc",
    "number": "123456789"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "null",
    "number": "0"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Arto Hellas",
    "number": "01234"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Delete me",
    "number": "123"
}