PUT http://localhost:3001/api/persons/643056a2fa872a42d46a0cdd
Content-Type: application/json

{
    "name": "abc",
    "number": "1234"
}

###
PUT http://localhost:3001/api/persons/643056a2fa872a42d46a0cdd
Content-Type: application/json

{
    "name": "ab",
    "number": "123"
}